---
name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0

      - name: ⬇️ Checkout repository
        uses: actions/checkout@v2

      - name: 🚧 Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: 🔄 Restore dependencies
        run: dotnet restore

      - name: 🛠 Build
        run: dotnet build --no-restore

      - name: 🧪 Test
        run: dotnet test --no-build
